#Simple-Drugs v2.7-DEV Created by xxCoderforlife
#If you need help find me on Discord or Spigot.
#Spigot: https://www.spigotmc.org/resources/simple-drugs-with-gui.9684/
#Discord: https://discord.com/invite/jnmKj7Z
Core:
 Drugs:
  Acid:
   Time:
    CONFUSION: 200
    HEALTH_BOOST: 2400
    NIGHT_VISION: 2400
    SLOW_FALLING: 2400
  Ciggy:
   Time:
    SLOW_DIGGING: 2400
    JUMP: 2400
    SATURATION: 2400
    DAMAGE_RESISTANCE: 2400
  Weed:
   Time:
    SLOW_DIGGING: 2400
    SLOW: 2400
    SLOW_FALLING: 2400
    LUCK: 2400
  Coke:
   Time:
    SPEED: 2400
    FASY_DIGGING: 2400
    INCREASE_DAMAGE: 2400
    DAMAGE_RESISTANCE: 2400
    HEALTH_BOOST: 2400
  Heroin:
   Time:
    SLOW: 2400
    WEAKNESS: 2400
    POISON: 2400
    UNLUCK: 2400
  Percocet:
   Time:
    SLOW: 2400
    CONFUSION: 200
    NIGHT_VISION: 2400
    LUCK: 2400
  Molly:
   Time:
    CONFUSION: 200
    FAST_DIGGING: 2400
    SPEED: 2400
    FIRE_RESISTANCE: 2400
    NIGHT_VISION: 2400
  Shrooms:
   Time:
    LUCK: 2400
    NIGHT_VISION: 2400
    CONFUSION: 200
    GLOWING: 2400
  Salvia:
   Time:
    NIGHT_VISION: 2400
    REGENERATION: 2400
    WEAKNESS: 2400
    GLOWING: 2400
  PCP:
   Time:
    DAMAGE_RESISTANCE: 2400
    BAD_OMEN: 2400
    CONFUSION: 200
  DMT:
   Time:
    DAMAGE_RESISTANCE: 2400
    SLOW_FALLING: 2400
    SLOWNESS: 2400
    GLOWING: 2400
  Alcohol:
   Time:
    SPEED: 2400
    NIGHT_VISION: 2400
    HUNGER: 2400
    CONFUSION: 200
  Flakka:
   Time:
    SPEED: 2400
    DAMAGE_RESISTANCE: 2400
    UNLUCK: 2400
    DOLPHINS_GRACE: 2400
  Meth:
   Time:
    ABSORPTION: 2400
    SLOWNESS: 2400
    WEAKNESS: 2400
    LEVITATION: 2400
  Ketamine:
   Time:
    NIGHT_VISION: 2400
    SPEED: 2400
    FAST_DIGGING: 2400
    CONFUSION: 200
    SLOW_FALLING: 2400
  BagOfDrugs:
   #If the player can move the bag in their Inventory
   CanMove: true
   #If the player can drop the bag
   CanDrop: false
   #Is the bag given on player join
   #If you set this to false use /drugs bagofdrugs to get it
   GiveOnJoin: true
   #If the Bag is dropped on death or not.
   DropOnDeath: false
   #If the player Keeps the Bag when they Respawn
   GiveOnRespawn: true
