name: SimpleDrugs
version: 2.6.4
authors: [xxCoderforlife]
main: me.Coderforlife.Drugs.Main
commands:
    drugs:
        description: For Drugs yo
        usage: /<command>
        aliases: [d]
    remove:
        description: Remove all Drugs
        aliases: [r]
    changelog:
        description: ChangeLog for SimpleDrugs
        aliases: [change,log,c]
    dreload:
        description: Reload for SimpleDrugs
        aliases: [re,l,load]
        
permissons:
    drugs.*:
     children:
      drugs.wart: true
      drugs.wheat: true
      drugs.sugar: true
      drugs.paper: true
      drugs.gun: true
      drugs.bone: true
      drugs.remove: true
      drugs.main: true
      drugs.changelog: true	  
      drugs.reload: true
    drugs.wheat:
        default: true
    drugs.sugar:
        default: true
    drugs.paper:
        default: true
    drugs.gun:
        default: true
    drugs.bone:
        default: true
    drugs.wart:
        default: true
    drugs.remove:
        default: true
    drugs.main:
        default: true
    drugs.reload:
        default: op