name: Simple Drugs
version: 2.5.4
athours: [xxCoderforlife]
main: me.Coderforlife.Drugs.Drugs
commands:
    drugs:
        description: For Drugs yo
        usage: /<command>
        aliases: [d]
    help:
        description: Drugs Help
        aliases: [h]
    remove:
        description: Remove all Drugs
        aliases: [r]
    changelog:
        description: ChangeLog for SimpleDrugs
        aliases: [change,log,c]
    dreload:
        description: Reload for SimpleDrugs
        aliases: [re,l,load]
        
permissons:
    drugs.wheat:
        default: true
    drugs.sugar:
        default: true
    drugs.paper:
        default: true
    drugs.gun:
        default: true
    drugs.bone:
        default: true
    drugs.remove:
        default: true
    drugs.reload:
        default: op
    