#========================[SIMPLE-DRUGS CONFIG]============================#
#Simple-Drugs v2.7-DEV Created by xxCoderforlife
#If you need help find me on Discord or Spigot.
#Spigot: https://www.spigotmc.org/resources/simple-drugs-with-gui.9684/
#Discord: https://discord.com/invite/jnmKj7Z
#               WIKI LINK: 
#    https://xxcoderforlife.gitbook.io/simpledrugswiki/
#=========================================================================#
Drugs:
  #If you want to even check for an update
  CheckForUpdate: true
  #If you want a message sent to players in game with the permission 'drugs.updater'
  UpdateMessage: false
  #Sends the player a plugin message on Join
  JoinMessage: true
  BagOfDrugs:
    #If the player can move the bag in their Inventory
    CanMove: false
    #If the player can drop the bag
    CanDrop: false
    #Is the bag given on player join
    #If you set this to false use /drugs bagofdrugs to get it
    GiveOnJoin: true
    #If the Bag is dropped on death or not.
    DropOnDeath: false
    #If the player Keeps the Bag when they Respawn
    GiveOnRespawn: true
#Yeah that's the end of the Config, You can find Drugs Settings in Drugs.json :)
