name: Patch and Build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Setup Maven with Java
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          java-distribution: 'temurin'
          maven-version: 3.9.9
      - name: Build
        run: mvn clean package
      - uses: actions/upload-artifact@v4
        with:
          name: "simple-drugs"
          path: "target/Simple-Drugs-*.jar"
